### ISSUE TITLE
FSR3 Upscaler

### ISSUE THREAD

**Issue by AndreiBazzaev** [blueskythlikesclouds/GenerationsRaytracing#1]
Good evening. I am implementing FSR3 Upscaling in my student project (an adaptation of Super Monkey Ball with path tracing). Is the setup for FSR that you created functional and can I reference it? Obviously, you will be mentioned in the project comments. Thanks in advance for the answer👍

**Comment by blueskythlikesclouds** [comment]
It is, yeah.
You don't need to give me any attribution.
